# NumPy - Numerical Python

## Criando arrays NumPy

In [1]:
# Importando o NumPy
import numpy as np

### Criando arrays de 1 dimensão

In [2]:
a1D = np.array([1, 2, 3])
a1D

array([1, 2, 3])

In [3]:
# O objeto criado é um ndarray: n-dimensional array
type(a1D)

numpy.ndarray

In [4]:
# Verificando o tipo dos elementos
a1D.dtype

dtype('int32')

In [5]:
b1D = np.array([1, 2, 3], dtype = float)
b1D

array([1., 2., 3.])

In [6]:
b1D.dtype

dtype('float64')

In [7]:
c1D = np.array([1, 2, 3], dtype = str)
c1D

array(['1', '2', '3'], dtype='<U1')

In [8]:
# str > float > int > bool
d1D = np.array([1, 3.14, "NumPy", True])
d1D

array(['1', '3.14', 'NumPy', 'True'], dtype='<U32')

In [16]:
d1D.dtype

dtype('<U32')

In [9]:
e1D = np.array([1, 3.14, False, True])
e1D


array([1.  , 3.14, 0.  , 1.  ])

In [10]:
e1D.dtype

dtype('float64')

In [11]:
f1D = np.array([1, False, True])
f1D

array([1, 0, 1])

In [12]:
f1D.dtype

dtype('int32')

In [13]:
g1D = np.array([False, True])
g1D

array([False,  True])

In [14]:
g1D.dtype

dtype('bool')

### Criando arrays de 2 dimensões

In [17]:
a2D = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9]])
a2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
a2D.dtype

dtype('int32')

### Criando arrays de 3 dimensões

In [19]:
a3D = np.array( [ [ [1,2,3], [4,5,6], [7,8,9] ], [ [11,12,13], [14,15,16], [17,18,19] ], [ [21,22,23], [24,25,26], [27,28,29] ]])
a3D

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

## Outras formas de criar arrays

### Arrays preenchidos com zeros - zeros()

In [20]:
# 1 dimensão
azeros = np.zeros(5)
azeros

array([0., 0., 0., 0., 0.])

In [21]:
# 2 dimensões
bzeros = np.zeros((3, 4)) # 3 linhas e 4 colunas
bzeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
# 3 dimensões
czeros = np.zeros((3, 4, 2)) # 3 páginas, 4 linhas e 2 colunas
czeros

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [23]:
# 2 dimensões
dzeros = np.zeros((3, 4), dtype = int) # 3 linhas e 4 colunas
dzeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### Arrays preenchidos com 1's - ones()

In [24]:
# 1 dimensão
a_um_1D = np.ones(5)
a_um_1D

array([1., 1., 1., 1., 1.])

In [25]:
b_um_1D = np.ones(10, dtype = str)
b_um_1D

array(['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'], dtype='<U1')

In [26]:
c_um_1D = np.ones(5, dtype = int)
c_um_1D

array([1, 1, 1, 1, 1])

In [27]:
# 2 dimensões
d_um_2D = np.ones((4, 3)) # 4 linhas e 3 colunas
d_um_2D

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
# 3 dimensões
e_um_3D = np.ones((5, 2, 3)) 
e_um_3D

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [29]:
# 4 dimensões
f_um_4D = np.ones((3, 4, 2, 3)) 
f_um_4D

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]])

### Arrays preenchidos com faixas de valores - arange()

In [30]:
# Cria um ndarray preenchido com  os elementos de 0 a n-1
# No exemplo abaixo vai criar um ndarray com os elementos 0 a 9
a1D = np.arange(10)
a1D

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# Cria um ndarray preenchido com os elementos variando entre o valor inicial e o valor final - 1
# Nesse exemplo vai criar um array com os elementos de 5 a 14
b1D = np.arange(5, 15)
b1D

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
# Cria um ndarray preenchido com os elementos variando entre o valor inicial e o valor final - 1, com um determinado step
# No exemplo vai criar um array com os elementos de 5 a 100, com passo 10. Ou seja: 5, 15, 25...95
c1D = np.arange(5,100, 10)
c1D

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

### Criando arrays preenchidos com valores igualmente espaçados - linspace()

In [33]:
# Cria um array com n elementos entre o valor inicial e valor final, igualmente espaçados
d1D = np.linspace(0,10, 2) # Cria um array com 2 valores entre 0 e 10
d1D

array([ 0., 10.])

In [34]:
e1D = np.linspace(0,10, 4) # Cria um array com 2 valores entre 0 e 10
e1D

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [35]:
f1D = np.linspace(1,1000) # Se não for passada a quantidade de elementos, o padrão é gerar 50 elementos
f1D

array([   1.        ,   21.3877551 ,   41.7755102 ,   62.16326531,
         82.55102041,  102.93877551,  123.32653061,  143.71428571,
        164.10204082,  184.48979592,  204.87755102,  225.26530612,
        245.65306122,  266.04081633,  286.42857143,  306.81632653,
        327.20408163,  347.59183673,  367.97959184,  388.36734694,
        408.75510204,  429.14285714,  449.53061224,  469.91836735,
        490.30612245,  510.69387755,  531.08163265,  551.46938776,
        571.85714286,  592.24489796,  612.63265306,  633.02040816,
        653.40816327,  673.79591837,  694.18367347,  714.57142857,
        734.95918367,  755.34693878,  775.73469388,  796.12244898,
        816.51020408,  836.89795918,  857.28571429,  877.67346939,
        898.06122449,  918.44897959,  938.83673469,  959.2244898 ,
        979.6122449 , 1000.        ])

In [36]:
g1D = np.linspace(1,1000, dtype = int) # gerando int, a função simplesmente corta as casas decimais
g1D

array([   1,   21,   41,   62,   82,  102,  123,  143,  164,  184,  204,
        225,  245,  266,  286,  306,  327,  347,  367,  388,  408,  429,
        449,  469,  490,  510,  531,  551,  571,  592,  612,  633,  653,
        673,  694,  714,  734,  755,  775,  796,  816,  836,  857,  877,
        898,  918,  938,  959,  979, 1000])

In [37]:
h1D = np.linspace(0,50, 10, endpoint = True) # O valor final é incluído
h1D


array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [38]:
i1D = np.linspace(0,50, 10, endpoint = False) # O valor final não é incluído
i1D

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.])

### Criando arrays preenchidos com um único valor passado por parâmetro - full()

In [39]:
a1D = np.full(10, 5) # ndarray contendo 10 números 5
a1D

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [40]:
a2D = np.full((3, 5), 3)  # ndarray de 3 linhas e 5 colunas contendo o número 3
a2D

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [41]:
a3D = np.full((3, 5, 8), -1)  # ndarray de 3 páginas, 5 linhas e 8 colunas contendo o número -1
a3D

array([[[-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1]],

       [[-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1]],

       [[-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1]]])

### Criando matriz identidade - eye()

In [42]:
ident = np.eye(5) # Cria uma matriz 5x5 preenchida com 1s na diagonal principal e 0 nas posições restantes
ident

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Criando matriz com elementos aleatórios

In [47]:
a1D = np.random.randint(0, 100, 10) # Cria um ndarray com 10 elementos entre 0 e 99
a1D

array([81, 19, 78, 74, 32, 47, 36, 39, 19, 27])

In [48]:
a2D = np.random.randint(1, 500, (4,5))
a2D

array([[398, 203,  56, 291, 207],
       [ 60, 316,  37, 293,  50],
       [ 87, 116, 285, 346,  23],
       [ 31, 382, 285, 395, 260]])

In [49]:
# Gerando 10 combinações para a mega-sena
# Valores vão de 1 a 60, 10 páginas, 1 linha, 6 colunas
a3D = np.random.randint(1,61,(10,1,6)) 
a3D

array([[[20, 34, 35,  2, 52, 55]],

       [[13,  5, 11, 51,  3, 12]],

       [[12, 44, 25, 58, 46, 31]],

       [[14, 41,  9,  5, 12,  7]],

       [[58,  2, 36, 49, 42, 46]],

       [[18, 37, 52, 45, 16, 28]],

       [[13, 20, 52, 52, 25, 15]],

       [[24, 44,  7, 35,  4, 22]],

       [[44, 15, 30, 15, 54,  9]],

       [[27, 57, 36, 36, 53,  9]]])

In [55]:
b1D = np.random.random(10) # Cria um ndarray contendo 10 elementos aleatórios entre 0 e 1
b1D

array([0.09266254, 0.46614866, 0.64223913, 0.10032058, 0.97229481,
       0.83255106, 0.3035005 , 0.50467621, 0.19662512, 0.11483917])

Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\Thiago\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Thiago\anaconda3\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma conexão existente pelo host remoto
Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\Thiago\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Thiago\anaconda3\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma

Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\Thiago\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Thiago\anaconda3\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma conexão existente pelo host remoto
Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\Thiago\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Thiago\anaconda3\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma

Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\Thiago\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Thiago\anaconda3\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma conexão existente pelo host remoto
Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\Thiago\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Thiago\anaconda3\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma

Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\Thiago\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Thiago\anaconda3\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma conexão existente pelo host remoto
Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\Thiago\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Thiago\anaconda3\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma

Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\Thiago\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Thiago\anaconda3\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma conexão existente pelo host remoto
Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\Thiago\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Thiago\anaconda3\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma

Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\Thiago\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Thiago\anaconda3\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma conexão existente pelo host remoto
Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\Thiago\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Thiago\anaconda3\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma

Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\Thiago\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Thiago\anaconda3\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma conexão existente pelo host remoto
Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\Thiago\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Thiago\anaconda3\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma

Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\Thiago\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Thiago\anaconda3\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma conexão existente pelo host remoto
Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\Thiago\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Thiago\anaconda3\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma

Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\Thiago\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Thiago\anaconda3\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma conexão existente pelo host remoto
Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\Thiago\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Thiago\anaconda3\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma

Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\Thiago\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Thiago\anaconda3\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma conexão existente pelo host remoto
Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\Thiago\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Thiago\anaconda3\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma

Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\Thiago\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Thiago\anaconda3\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma conexão existente pelo host remoto
Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\Users\Thiago\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Thiago\anaconda3\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma

In [51]:
c2D = np.random.random((4,5)) # Cria um ndarray de 4 linhas e 5 colunas contendo elementos aleatórios entre 0 e 1
c2D

array([[0.69836077, 0.84900475, 0.11691753, 0.0799246 , 0.18912333],
       [0.51003672, 0.17994476, 0.37313692, 0.8013451 , 0.72093307],
       [0.58858114, 0.54449607, 0.09141093, 0.016509  , 0.80878628],
       [0.32532462, 0.54129512, 0.57192524, 0.83342894, 0.20119124]])