# Indexação e fatiamento (slicing)

In [1]:
# Importando o NumPy
import numpy as np

In [2]:
# Cria um ndarray com 10 elementos entre 0 e 9
a1D = np.random.randint(0, 10, 10)
a1D

array([6, 0, 4, 0, 2, 0, 1, 1, 1, 7])

In [3]:
a2D = np.random.randint(1, 101, (4,5)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[ 7, 13, 56, 98, 45],
       [71, 77, 31, 38, 94],
       [90, 59,  2, 57, 92],
       [89, 41, 77, 64, 68]])

In [4]:
a3D = np.random.random((3,4,5)) # Cria um ndarray de 3 páginas x 4 linhas x 5 colunas com elementos entre 0 e 1
a3D

array([[[0.22313423, 0.96459802, 0.81003979, 0.3202331 , 0.79970301],
        [0.64108078, 0.51320579, 0.48977679, 0.10091575, 0.17744863],
        [0.08019348, 0.42284109, 0.67783351, 0.10120957, 0.52449624],
        [0.7806066 , 0.86074008, 0.00397581, 0.60444499, 0.97808371]],

       [[0.23864549, 0.11876185, 0.15610741, 0.3434204 , 0.62135074],
        [0.08612984, 0.83787888, 0.77520181, 0.67011204, 0.93971613],
        [0.14844687, 0.17499219, 0.02590024, 0.30385154, 0.66981505],
        [0.86488713, 0.33308853, 0.13260632, 0.88356567, 0.22942502]],

       [[0.18078672, 0.94616265, 0.80733066, 0.69472685, 0.05913967],
        [0.73897772, 0.63404432, 0.53994421, 0.97825092, 0.85408167],
        [0.40213028, 0.5080866 , 0.78488739, 0.11976166, 0.66189864],
        [0.07797954, 0.09417865, 0.87586133, 0.68691576, 0.52589568]]])

### Acessando elementos específicos

In [5]:
# Acessando elementos de um ndarray de 1 dimensão
a1D

array([6, 0, 4, 0, 2, 0, 1, 1, 1, 7])

In [6]:
# nome_do_array[índice]
a1D[0]

6

In [7]:
a1D[2]

4

In [8]:
a1D[-1]

7

In [9]:
indices = [3, 0, -1] # Definindo uma lista com os índices que se deseja acessar
a1D[indices]

array([0, 6, 7])

In [10]:
# Acessando elementos de um ndarray de 2 dimensões
a2D

array([[ 7, 13, 56, 98, 45],
       [71, 77, 31, 38, 94],
       [90, 59,  2, 57, 92],
       [89, 41, 77, 64, 68]])

In [11]:
# nome_da_matriz[linha][coluna]
a2D[1][2]

31

In [12]:
a2D[3][4]

68

In [13]:
indice_lin = [0, 1, 2, 3]
indice_col = [0, 1, 2, 3]

a2D[indice_lin, indice_col]

array([ 7, 77,  2, 64])

In [14]:
indice_lin = [0, 1, 2, 3]
indice_col = [3, 2, 1, 0]

a2D[indice_lin, indice_col]

array([98, 31, 59, 89])

In [16]:
indice_lin = [3, 2, 1, 0]
indice_col = [3, 2, 1, 0]

a2D[indice_lin, indice_col]

array([64,  2, 77,  7])

In [17]:
a2D[:,[0,1,2,0]] 

array([[ 7, 13, 56,  7],
       [71, 77, 31, 71],
       [90, 59,  2, 90],
       [89, 41, 77, 89]])

In [18]:
a2D[:,[0,1,2,0]][[1, 0, 1, 0]]

array([[71, 77, 31, 71],
       [ 7, 13, 56,  7],
       [71, 77, 31, 71],
       [ 7, 13, 56,  7]])

In [19]:
a2D

array([[ 7, 13, 56, 98, 45],
       [71, 77, 31, 38, 94],
       [90, 59,  2, 57, 92],
       [89, 41, 77, 64, 68]])

In [20]:
a2D[[1, 0, 1, 0]][:,[0,1,2,0]] 

array([[71, 77, 31, 71],
       [ 7, 13, 56,  7],
       [71, 77, 31, 71],
       [ 7, 13, 56,  7]])

In [21]:
# Acessando elementos de um ndarray de 3 dimensões
a3D

array([[[0.22313423, 0.96459802, 0.81003979, 0.3202331 , 0.79970301],
        [0.64108078, 0.51320579, 0.48977679, 0.10091575, 0.17744863],
        [0.08019348, 0.42284109, 0.67783351, 0.10120957, 0.52449624],
        [0.7806066 , 0.86074008, 0.00397581, 0.60444499, 0.97808371]],

       [[0.23864549, 0.11876185, 0.15610741, 0.3434204 , 0.62135074],
        [0.08612984, 0.83787888, 0.77520181, 0.67011204, 0.93971613],
        [0.14844687, 0.17499219, 0.02590024, 0.30385154, 0.66981505],
        [0.86488713, 0.33308853, 0.13260632, 0.88356567, 0.22942502]],

       [[0.18078672, 0.94616265, 0.80733066, 0.69472685, 0.05913967],
        [0.73897772, 0.63404432, 0.53994421, 0.97825092, 0.85408167],
        [0.40213028, 0.5080866 , 0.78488739, 0.11976166, 0.66189864],
        [0.07797954, 0.09417865, 0.87586133, 0.68691576, 0.52589568]]])

In [22]:
# nome_do_cubo[página][linha][coluna]
a3D[2][0][3]

0.6947268540223354

In [23]:
a3D[0][3][1]

0.8607400822030384

### Fatiamento (slicing)

In [24]:
# Array de 1 dimensão
a1D

array([6, 0, 4, 0, 2, 0, 1, 1, 1, 7])

In [25]:
a = a1D[1:5] # Índice 1 ao 4
a

array([0, 4, 0, 2])

In [26]:
b = a1D[0:6] # Índice 0 ao 5
b

array([6, 0, 4, 0, 2, 0])

In [27]:
c = a1D[:6] # Do início ao 5
c

array([6, 0, 4, 0, 2, 0])

In [29]:
d = a1D[::2] # Do início ao fim, com passo 2
d

array([6, 4, 2, 1, 1])

In [30]:
e = a1D[-1::-1] # Do final até o início
e

array([7, 1, 1, 1, 0, 2, 0, 4, 0, 6])

In [31]:
# Array de 2 dimensões
a2D

array([[ 7, 13, 56, 98, 45],
       [71, 77, 31, 38, 94],
       [90, 59,  2, 57, 92],
       [89, 41, 77, 64, 68]])

In [32]:
linha0 = a2D[0] # Todos os elementos da linha 0 - outra forma seria: linha0 = a2D[0,:]
linha0

array([ 7, 13, 56, 98, 45])

In [33]:
linha1 = a2D[1,:] # Todos os elementos da linha 1
linha1

array([71, 77, 31, 38, 94])

In [34]:
linha2 = a2D[2,1:4] # Linha 2, colunas 1, 2 e 3
linha2

array([59,  2, 57])

In [36]:
linha3 = a2D[:][3] # a2D[:] retorna toda a matriz, então de toda a matriz queremos a linha 3 a2D[:][3]
linha3

array([89, 41, 77, 64, 68])

In [37]:
coluna2 = a2D[:,2] # De todas as linhas, selecionar a coluna 2
coluna2

array([56, 31,  2, 77])

In [38]:
coluna3 = a2D[1:,3] # Da linha um até a última, selecionar a coluna 3
coluna3

array([38, 57, 64])

In [39]:
# Array de 3 dimensões
a3D

array([[[0.22313423, 0.96459802, 0.81003979, 0.3202331 , 0.79970301],
        [0.64108078, 0.51320579, 0.48977679, 0.10091575, 0.17744863],
        [0.08019348, 0.42284109, 0.67783351, 0.10120957, 0.52449624],
        [0.7806066 , 0.86074008, 0.00397581, 0.60444499, 0.97808371]],

       [[0.23864549, 0.11876185, 0.15610741, 0.3434204 , 0.62135074],
        [0.08612984, 0.83787888, 0.77520181, 0.67011204, 0.93971613],
        [0.14844687, 0.17499219, 0.02590024, 0.30385154, 0.66981505],
        [0.86488713, 0.33308853, 0.13260632, 0.88356567, 0.22942502]],

       [[0.18078672, 0.94616265, 0.80733066, 0.69472685, 0.05913967],
        [0.73897772, 0.63404432, 0.53994421, 0.97825092, 0.85408167],
        [0.40213028, 0.5080866 , 0.78488739, 0.11976166, 0.66189864],
        [0.07797954, 0.09417865, 0.87586133, 0.68691576, 0.52589568]]])

In [40]:
# Acessando a página/face 1
face1 = a3D[1]
face1

array([[0.76163608, 0.09862463, 0.55179373, 0.04544569, 0.48611129],
       [0.58757544, 0.7183161 , 0.55202015, 0.52033372, 0.14960717],
       [0.66213795, 0.97147589, 0.0595247 , 0.11927832, 0.65942077],
       [0.52477627, 0.53551621, 0.76811475, 0.06466217, 0.22687256]])

In [41]:
# Acessando uma parte da face1
subface1 = a3D[1,0:3, 1:4]
subface1

array([[0.11876185, 0.15610741, 0.3434204 ],
       [0.83787888, 0.77520181, 0.67011204],
       [0.17499219, 0.02590024, 0.30385154]])

In [42]:
linha2face0 = a3D[0,2] # outra forma: linha2face0 = a3D[0,2,:]
linha2face0

array([0.08019348, 0.42284109, 0.67783351, 0.10120957, 0.52449624])

In [43]:
a3D

array([[[0.22313423, 0.96459802, 0.81003979, 0.3202331 , 0.79970301],
        [0.64108078, 0.51320579, 0.48977679, 0.10091575, 0.17744863],
        [0.08019348, 0.42284109, 0.67783351, 0.10120957, 0.52449624],
        [0.7806066 , 0.86074008, 0.00397581, 0.60444499, 0.97808371]],

       [[0.23864549, 0.11876185, 0.15610741, 0.3434204 , 0.62135074],
        [0.08612984, 0.83787888, 0.77520181, 0.67011204, 0.93971613],
        [0.14844687, 0.17499219, 0.02590024, 0.30385154, 0.66981505],
        [0.86488713, 0.33308853, 0.13260632, 0.88356567, 0.22942502]],

       [[0.18078672, 0.94616265, 0.80733066, 0.69472685, 0.05913967],
        [0.73897772, 0.63404432, 0.53994421, 0.97825092, 0.85408167],
        [0.40213028, 0.5080866 , 0.78488739, 0.11976166, 0.66189864],
        [0.07797954, 0.09417865, 0.87586133, 0.68691576, 0.52589568]]])

In [44]:
linha1todasfaces = a3D[:,1] # outra forma: linha1todasfaces = a3D[:,1,:]
linha1todasfaces

array([[0.64108078, 0.51320579, 0.48977679, 0.10091575, 0.17744863],
       [0.08612984, 0.83787888, 0.77520181, 0.67011204, 0.93971613],
       [0.73897772, 0.63404432, 0.53994421, 0.97825092, 0.85408167]])

In [45]:
coluna3todasfaces = a3D[:,:,3]
coluna3todasfaces

array([[0.3202331 , 0.10091575, 0.10120957, 0.60444499],
       [0.3434204 , 0.67011204, 0.30385154, 0.88356567],
       [0.69472685, 0.97825092, 0.11976166, 0.68691576]])

### Indexação com booleanos

In [46]:
a2D = np.random.randint(1, 501, (10, 8)) # Cria um ndarray de 10 linhas x 8 colunas com elementos entre 1 e 500
a2D

array([[ 95, 132, 202,  72,  74, 422, 432, 207],
       [147, 431,  27, 146, 447,   3, 421, 422],
       [254, 424, 317,  22, 184, 115, 387, 133],
       [ 47, 480, 217, 146, 163, 454, 364, 135],
       [496,  87, 277, 192, 229, 334, 463,  33],
       [ 40, 282,  95, 316, 356, 405,  69, 320],
       [336, 337, 454,  56, 135, 253,   6, 160],
       [ 89, 175, 465, 392, 279, 486, 413,  11],
       [253, 489, 145, 110, 471, 187, 305,  11],
       [394, 149, 229,  78, 114, 472, 100,   6]])

In [47]:
a2D >= 250

array([[False, False, False, False, False,  True,  True, False],
       [False,  True, False, False,  True, False,  True,  True],
       [ True,  True,  True, False, False, False,  True, False],
       [False,  True, False, False, False,  True,  True, False],
       [ True, False,  True, False, False,  True,  True, False],
       [False,  True, False,  True,  True,  True, False,  True],
       [ True,  True,  True, False, False,  True, False, False],
       [False, False,  True,  True,  True,  True,  True, False],
       [ True,  True, False, False,  True, False,  True, False],
       [ True, False, False, False, False,  True, False, False]])

In [48]:
a2D[a2D >= 250]

array([422, 432, 431, 447, 421, 422, 254, 424, 317, 387, 480, 454, 364,
       496, 277, 334, 463, 282, 316, 356, 405, 320, 336, 337, 454, 253,
       465, 392, 279, 486, 413, 253, 489, 471, 305, 394, 472])

In [55]:
a2D.mean()

238.45

In [56]:
a2D[a2D <= a2D.mean()]

array([ 95, 132, 202,  72,  74, 207, 147,  27, 146,   3,  22, 184, 115,
       133,  47, 217, 146, 163, 135,  87, 192, 229,  33,  40,  95,  69,
        56, 135,   6, 160,  89, 175,  11, 145, 110, 187,  11, 149, 229,
        78, 114, 100,   6])