# Manipulação de arrays Numpy

### Importando o NumPy

In [1]:
# Importando o NumPy
import numpy as np

### Alterando, adicionando e removendo elementos

In [3]:
# Criando um array de 1 dimensão
a1D = np.random.randint(1,200, 12)
a1D

array([122,  85,  65, 195, 108, 148, 133, 123,  25, 108,  18,  37])

In [4]:
# Criando um array de 2 dimensões
a2D = np.random.randint(1,200, (3,4))
a2D

array([[ 73,   3, 107, 158],
       [104, 137, 151,   9],
       [ 97, 167, 183, 164]])

In [5]:
# Criando um array de 3 dimensões
a3D = np.random.randint(1,200, (2,3,6)) # 2 páginas/faces, 3 linhas, 6 colunas
a3D

array([[[ 18,  41,  18,  26, 183, 182],
        [ 28,  16,  90,   7,  20,  78],
        [194, 166, 165, 170,  86,  20]],

       [[ 58,  60, 193, 178, 139,   4],
        [133,  58,  70,  64,  85, 183],
        [ 58, 192, 191,  25,  85, 135]]])

In [6]:
# Alterando o elemento do índice 0
a1D[0] = -1
a1D

array([ -1,  85,  65, 195, 108, 148, 133, 123,  25, 108,  18,  37])

In [7]:
# Alterando o elemento da linha 1, coluna 2
a2D[1][2] = -1
a2D

array([[ 73,   3, 107, 158],
       [104, 137,  -1,   9],
       [ 97, 167, 183, 164]])

In [8]:
# Alterando o elemento da face 1, linha 2, coluna 4
a3D[1][2][4] = -1
a3D

array([[[ 18,  41,  18,  26, 183, 182],
        [ 28,  16,  90,   7,  20,  78],
        [194, 166, 165, 170,  86,  20]],

       [[ 58,  60, 193, 178, 139,   4],
        [133,  58,  70,  64,  85, 183],
        [ 58, 192, 191,  25,  -1, 135]]])

In [9]:
# Retorna array com elementos adicionados no final
a1D_modificado = np.append(a1D, [100, 130])
a1D_modificado

array([ -1,  85,  65, 195, 108, 148, 133, 123,  25, 108,  18,  37, 100,
       130])

In [10]:
a1D # a1D não foi modificado

array([ -1,  85,  65, 195, 108, 148, 133, 123,  25, 108,  18,  37])

In [11]:
a2D_modificado = np.append(a2D, [100, 130]) # Lineariza a2D e insere os elementos no final
a2D_modificado

array([ 73,   3, 107, 158, 104, 137,  -1,   9,  97, 167, 183, 164, 100,
       130])

In [12]:
a2D # a2D não foi modificado

array([[ 73,   3, 107, 158],
       [104, 137,  -1,   9],
       [ 97, 167, 183, 164]])

In [13]:
a3D_modificado = np.append(a3D, [100, 130]) # Lineariza a3D e insere os elementos no final
a3D_modificado

array([ 18,  41,  18,  26, 183, 182,  28,  16,  90,   7,  20,  78, 194,
       166, 165, 170,  86,  20,  58,  60, 193, 178, 139,   4, 133,  58,
        70,  64,  85, 183,  58, 192, 191,  25,  -1, 135, 100, 130])

In [14]:
a3D # a3D não foi modificado

array([[[ 18,  41,  18,  26, 183, 182],
        [ 28,  16,  90,   7,  20,  78],
        [194, 166, 165, 170,  86,  20]],

       [[ 58,  60, 193, 178, 139,   4],
        [133,  58,  70,  64,  85, 183],
        [ 58, 192, 191,  25,  -1, 135]]])

In [15]:
a1D_modificado2 = np.delete(a1D_modificado, [0, 1, 3])
print(a1D_modificado)
print(a1D_modificado2)

[ -1  85  65 195 108 148 133 123  25 108  18  37 100 130]
[ 65 108 148 133 123  25 108  18  37 100 130]


### Comparação entre arrays

In [16]:
a1D = np.array([1, 2, 3, 4, 5])
b1D = np.array([3, 2, 1, 4, 5])
a1D == b1D # Comparação elemento a elemento

array([False,  True, False,  True,  True])

In [17]:
c1D = np.random.randint(1,10,20)
c1D

array([6, 4, 6, 1, 7, 1, 5, 6, 1, 9, 9, 8, 4, 2, 2, 3, 2, 4, 9, 4])

In [18]:
c1D == 5

array([False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [19]:
c1D[c1D == 5]

array([5])

### Operações entre arrays e escalares

In [20]:
a1D = np.arange(1,11)
a1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
b1D = np.arange(1,20,2)
b1D

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [22]:
c1D = 2 * a1D # Cada elemento de a1D será multiplicado por 2
c1D

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [23]:
d1D = b1D + 5 # Soma 5 para cada elemento de b1D
d1D

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [24]:
e1D = b1D - 3
e1D

array([-2,  0,  2,  4,  6,  8, 10, 12, 14, 16])

In [25]:
f1D = a1D / 5
f1D

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [26]:
celsius = np.arange(-20, 36) # Cria um array com o valores de -20 a 35, representando a temperatura em graus Celsius
fahrenheit = celsius * (9/5) + 32 # Cria um array convertendo cada valor em Celsius para fahrenheit

fahrenheit

array([-4. , -2.2, -0.4,  1.4,  3.2,  5. ,  6.8,  8.6, 10.4, 12.2, 14. ,
       15.8, 17.6, 19.4, 21.2, 23. , 24.8, 26.6, 28.4, 30.2, 32. , 33.8,
       35.6, 37.4, 39.2, 41. , 42.8, 44.6, 46.4, 48.2, 50. , 51.8, 53.6,
       55.4, 57.2, 59. , 60.8, 62.6, 64.4, 66.2, 68. , 69.8, 71.6, 73.4,
       75.2, 77. , 78.8, 80.6, 82.4, 84.2, 86. , 87.8, 89.6, 91.4, 93.2,
       95. ])

In [27]:
# Somando cada elemento de a1D a b1D
g1D = a1D + b1D
print(a1D)
print(b1D)
print("-"*31)
print(g1D)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13 15 17 19]
-------------------------------
[ 2  5  8 11 14 17 20 23 26 29]


In [28]:
# Outra forma de somar cada elemento de a1D a b1D
h1D = np.add(a1D, b1D)
print(a1D)
print(b1D)
print("-"*31)
print(h1D)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13 15 17 19]
-------------------------------
[ 2  5  8 11 14 17 20 23 26 29]


In [29]:
i1D = h1D - g1D
print(h1D)
print(g1D)
print("-"*31)
print(i1D)

[ 2  5  8 11 14 17 20 23 26 29]
[ 2  5  8 11 14 17 20 23 26 29]
-------------------------------
[0 0 0 0 0 0 0 0 0 0]


In [30]:
# Outra forma de somar cada elemento de a1D a b1D
j1D = np.subtract(h1D, g1D)
print(h1D)
print(g1D)
print("-"*31)
print(j1D)

[ 2  5  8 11 14 17 20 23 26 29]
[ 2  5  8 11 14 17 20 23 26 29]
-------------------------------
[0 0 0 0 0 0 0 0 0 0]


In [31]:
a1D = np.arange(1, 6)
a1D

array([1, 2, 3, 4, 5])

In [32]:
b1D = np.arange(6,11)
b1D

array([ 6,  7,  8,  9, 10])

In [33]:
c1D = a1D * b1D
c1D

array([ 6, 14, 24, 36, 50])

In [34]:
d1D = np.multiply(a1D, b1D)
d1D

array([ 6, 14, 24, 36, 50])

In [35]:
e1D = c1D / a1D
e1D

array([ 6.,  7.,  8.,  9., 10.])

In [36]:
f1D = np.divide(c1D, a1D)
f1D

array([ 6.,  7.,  8.,  9., 10.])

In [37]:
g1D = np.arange(1,10)
g1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
raiz1D = np.sqrt(g1D)
raiz1D

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

### Algumas funções

In [3]:
d2D = np.random.randint(1, 101, (5,10)) # Array de 5 linhas x 10 colunas preenchidos com valores aleatórios entre 1 e 100
d2D

array([[97, 75,  5, 18, 57, 65,  7, 12, 84, 38],
       [96, 23, 72, 33, 20, 38, 55, 16, 60, 39],
       [97, 86, 69, 88, 74, 27, 92, 91, 10, 16],
       [18, 22, 89, 30, 19, 20, 98, 48,  2, 59],
       [63, 37, 92, 57, 42, 95, 50, 54, 71,  4]])

#### Obs: como os valores valores são gerados aleatoriamente, sua matriz provavelmente será diferente da gerada acima

In [40]:
# Soma de todos os elementos
d2D.sum()

2839

In [41]:
# Soma de todos os elementos de cada coluna (eixo 0)
d2D.sum(axis = 0)

array([325, 337, 310, 266, 211, 311, 318, 234, 298, 229])

In [42]:
# Soma de todos os elementos de cada linha (eixo 1)
d2D.sum(axis = 1)

array([678, 596, 460, 596, 509])

In [43]:
somacol = sum(d2D) # A função sum() do Python retornará a soma de todas as colunas
somacol

array([325, 337, 310, 266, 211, 311, 318, 234, 298, 229])

In [44]:
# Retorna o menor valor geral
d2D.min()

1

In [45]:
# Retorna o menor valor de cada coluna (eixo 0)
d2D.min(axis=0)

array([36, 12, 21,  3, 10, 48, 25,  1, 19, 27])

In [46]:
# Retorna o menor valor de cada linha (eixo 1)
d2D.min(axis=1)

array([19, 27, 19,  1,  3])

In [47]:
# Retorna o maior valor geral
d2D.max()

98

In [48]:
# Retorna o maior valor de cada coluna (eixo 0)
d2D.max(axis=0)

array([85, 94, 95, 98, 69, 97, 98, 98, 98, 98])

In [49]:
# Retorna o maior valor de cada linha (eixo 1)
d2D.max(axis=1)

array([98, 98, 98, 88, 98])

In [52]:
# Retorna a soma cumulativa
d2D.cumsum()

array([  84,  173,  268,  287,  349,  397,  495,  551,  649,  678,  719,
        813,  879,  977, 1024, 1074, 1160, 1200, 1247, 1274, 1310, 1383,
       1404, 1467, 1490, 1555, 1580, 1678, 1697, 1734, 1813, 1882, 1970,
       2053, 2122, 2173, 2249, 2250, 2292, 2330, 2415, 2427, 2467, 2470,
       2480, 2577, 2610, 2649, 2741, 2839], dtype=int32)

In [53]:
# Retorna a soma cumulativa para cada coluna (eixo = 0)
d2D.cumsum(axis = 0)

array([[ 84,  89,  95,  19,  62,  48,  98,  56,  98,  29],
       [125, 183, 161, 117, 109,  98, 184,  96, 145,  56],
       [161, 256, 182, 180, 132, 163, 209, 194, 164,  93],
       [240, 325, 270, 263, 201, 214, 285, 195, 206, 131],
       [325, 337, 310, 266, 211, 311, 318, 234, 298, 229]], dtype=int32)

In [51]:
d2D

array([[84, 89, 95, 19, 62, 48, 98, 56, 98, 29],
       [41, 94, 66, 98, 47, 50, 86, 40, 47, 27],
       [36, 73, 21, 63, 23, 65, 25, 98, 19, 37],
       [79, 69, 88, 83, 69, 51, 76,  1, 42, 38],
       [85, 12, 40,  3, 10, 97, 33, 39, 92, 98]])

In [54]:
# Retorna a soma cumulativa para cada linha (eixo = 1)
x = d2D.cumsum(axis = 1)
x

array([[ 84, 173, 268, 287, 349, 397, 495, 551, 649, 678],
       [ 41, 135, 201, 299, 346, 396, 482, 522, 569, 596],
       [ 36, 109, 130, 193, 216, 281, 306, 404, 423, 460],
       [ 79, 148, 236, 319, 388, 439, 515, 516, 558, 596],
       [ 85,  97, 137, 140, 150, 247, 280, 319, 411, 509]], dtype=int32)

In [55]:
# Retorna a média aritmética
d2D.mean()

56.78

In [56]:
# Retorna a média aritmética para cada coluna (eixo = 0)
d2D.mean(axis = 0)

array([65. , 67.4, 62. , 53.2, 42.2, 62.2, 63.6, 46.8, 59.6, 45.8])

In [57]:
# Retorna a média aritmética para cada linha (eixo = 1)
d2D.mean(axis = 1)

array([67.8, 59.6, 46. , 59.6, 50.9])

In [58]:
# Retorna o desvio padrão
d2D.std()

29.159074059373012

In [59]:
# Retorna o desvio padrão para cada coluna (eixo = 0)
d2D.std(axis = 0)

array([21.78990592, 29.24790591, 28.09270368, 36.5535224 , 22.53353057,
       18.41086636, 29.20684851, 31.33943203, 30.46703136, 26.45297715])

In [60]:
# Retorna o desvio padrão para cada linha (eixo = 1)
d2D.std(axis = 1)

array([27.79856111, 23.66093827, 25.66709956, 25.41731693, 36.41002609])

In [61]:
# Retorna a mediana (geral)
np.median(d2D)

53.5

In [7]:
# Retorna a mediana para cada coluna (eixo = 0)
np.median(d2D, axis = 0)

array([96., 37., 72., 33., 42., 38., 55., 48., 60., 38.])

In [9]:
#Retorna a mediana para cada linha (eixo = 1)
np.median(d2D, axis = 1)

array([47.5, 38.5, 80. , 26. , 55.5])

### Copiando e concatenando arrays

In [10]:
a2D = np.random.randint(1,50, (4,5))
a2D

array([[ 4,  5, 14,  7, 21],
       [18, 12,  8, 15, 46],
       [45, 24, 42, 18,  9],
       [21, 48,  2, 36,  4]])

In [11]:
b2D = np.random.randint(50,100, (4,5))
b2D

array([[92, 54, 94, 75, 79],
       [84, 90, 87, 56, 83],
       [69, 64, 57, 72, 93],
       [99, 88, 90, 58, 70]])

In [12]:
c2D = a2D
c2D

array([[ 4,  5, 14,  7, 21],
       [18, 12,  8, 15, 46],
       [45, 24, 42, 18,  9],
       [21, 48,  2, 36,  4]])

In [13]:
# Aparentemente ocorreu uma cópia dos arrays, mas veja o que acontece se alterarmos alguns elementos
c2D[c2D < 20] = -1
c2D

array([[-1, -1, -1, -1, 21],
       [-1, -1, -1, -1, 46],
       [45, 24, 42, -1, -1],
       [21, 48, -1, 36, -1]])

In [14]:
a2D 

array([[-1, -1, -1, -1, 21],
       [-1, -1, -1, -1, 46],
       [45, 24, 42, -1, -1],
       [21, 48, -1, 36, -1]])

Os elementos de a2D também foram alterados. :-(

In [15]:
# Redefinindo os elementos de a2D
a2D = np.random.randint(1,50, (4,5))
a2D

array([[33,  8, 43,  7, 35],
       [24, 17, 25, 12,  9],
       [42,  5, 33, 39, 41],
       [42, 45, 40, 23, 10]])

In [16]:
# Forma correta de copiar um array parece que com a forma de copiar uma lista
c2D = a2D.copy()
c2D

array([[33,  8, 43,  7, 35],
       [24, 17, 25, 12,  9],
       [42,  5, 33, 39, 41],
       [42, 45, 40, 23, 10]])

In [17]:
c2D[c2D < 20] = -1
c2D

array([[33, -1, 43, -1, 35],
       [24, -1, 25, -1, -1],
       [42, -1, 33, 39, 41],
       [42, 45, 40, 23, -1]])

In [18]:
a2D

array([[33,  8, 43,  7, 35],
       [24, 17, 25, 12,  9],
       [42,  5, 33, 39, 41],
       [42, 45, 40, 23, 10]])

Agora sim!!!

### Ordenando os elementos de um array

In [7]:
a1D = np.random.randint(1,100, 15)
a1D

array([ 6,  2, 49, 77,  8, 88, 38, 15, 93, 90,  6, 65, 45, 53, 83])

In [22]:
a1D.sort()
a1D

array([ 8,  8, 13, 16, 16, 22, 23, 26, 41, 51, 64, 85, 92, 93, 96])

In [23]:
a2D = np.random.randint(1,100, (6,10))
a2D

array([[85, 60, 78, 41, 88, 55,  6, 38, 19, 89],
       [55, 56, 68, 86, 94, 16, 97, 12, 59, 26],
       [25, 53, 60, 39, 95, 56, 92, 64, 76, 15],
       [71, 90, 49, 20, 40, 20, 60, 11, 41, 98],
       [48, 23, 55,  7, 82, 92, 68, 78, 63, 21],
       [82, 58, 51, 54, 92,  5, 56, 12, 87,  6]])

In [24]:
a2D.sort() # Por padrão ordena o maior eixo (nesse caso o eixo 1, linhas)
a2D

array([[ 6, 19, 38, 41, 55, 60, 78, 85, 88, 89],
       [12, 16, 26, 55, 56, 59, 68, 86, 94, 97],
       [15, 25, 39, 53, 56, 60, 64, 76, 92, 95],
       [11, 20, 20, 40, 41, 49, 60, 71, 90, 98],
       [ 7, 21, 23, 48, 55, 63, 68, 78, 82, 92],
       [ 5,  6, 12, 51, 54, 56, 58, 82, 87, 92]])

In [25]:
a2D.sort(axis=0) # Ordenando pelo eixo 0 (colunas)
a2D

array([[ 5,  6, 12, 40, 41, 49, 58, 71, 82, 89],
       [ 6, 16, 20, 41, 54, 56, 60, 76, 87, 92],
       [ 7, 19, 23, 48, 55, 59, 64, 78, 88, 92],
       [11, 20, 26, 51, 55, 60, 68, 82, 90, 95],
       [12, 21, 38, 53, 56, 60, 68, 85, 92, 97],
       [15, 25, 39, 55, 56, 63, 78, 86, 94, 98]])

In [26]:
a2D = np.random.randint(1,100, (6,10))
a2D

array([[55, 26, 22, 25, 96, 89, 98, 38, 48, 22],
       [75, 67, 55, 91,  2, 99, 59, 30, 31, 79],
       [14, 89,  9, 40, 74, 73, 74, 86, 21, 58],
       [85, 49, 70, 42, 48, 12, 20, 29, 12, 91],
       [71, 54, 13, 11, 57, 77, 84, 59, 69, 15],
       [97, 94, 97, 39, 44, 63, 13, 19, 88, 66]])

In [27]:
a2D.sort(axis=1) # Ordenando pelo eixo 1 (linhas)
a2D

array([[22, 22, 25, 26, 38, 48, 55, 89, 96, 98],
       [ 2, 30, 31, 55, 59, 67, 75, 79, 91, 99],
       [ 9, 14, 21, 40, 58, 73, 74, 74, 86, 89],
       [12, 12, 20, 29, 42, 48, 49, 70, 85, 91],
       [11, 13, 15, 54, 57, 59, 69, 71, 77, 84],
       [13, 19, 39, 44, 63, 66, 88, 94, 97, 97]])

### Transposição de arrays

In [3]:
a2D = np.array([[1,2,3,4],[5,6,7,8]])
a2D

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
a2DT = a2D.T # Retorna a transposta
a2DT

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [30]:
a2D # a2D original não foi transposto

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
a2D.transpose() # Retorna a transposta

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [32]:
a2D # a2D original não foi transposto

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Mudando o formato de um array - reshape()

In [10]:
a1D = np.arange(1,25)
a1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [11]:
print(a1D.shape)
a1D.shape = (2,12)
print(a1D.shape)
print(a1D)

(24,)
(2, 12)
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [12]:
a2D_4x6 = a1D.reshape(4,6)
a2D_4x6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [13]:
a1D

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [14]:
a2D_3x8 = a1D.reshape(3,8)
a2D_3x8

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

### Linearização de um array

In [15]:
x = a2D_3x8.flatten()
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [16]:
y = a2D_3x8.ravel()
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

### Combinando/concatenando arrays

In [17]:
a2D = np.random.randint(1,101,(3,9))
a2D

array([[10, 57, 61, 55, 57, 13,  3, 35, 67],
       [ 6, 58,  1, 18, 47, 54, 21, 44, 23],
       [51, 50, 69, 85, 68, 32, 21, 96, 71]])

In [18]:
b2D = np.random.randint(1,101,(5,9))
b2D

array([[ 42,  19,  75,  74,  35, 100,  35,  16,  36],
       [ 98,  35,  88,  25,   7,  24,   7,  30,  41],
       [ 98,  28,  10,   6,  14,  84,  64,  39,  38],
       [ 80,  77,   2,   6,  62,  28,  73,   4,  95],
       [ 99,  52,  10,   6,  12,  47,  22,  64,  89]])

In [19]:
c2D = np.random.randint(1,101,(5,4))
c2D

array([[44, 52, 69,  3],
       [83, 45, 31, 26],
       [78, 88,  4, 30],
       [21, 41, 79, 23],
       [49, 58, 27, 58]])

In [20]:
# Concatenação de strings usa o operador "+"
str1 = "Python"
str2 = " & "
str3 = "Numpy"
str4 = str1 + str2 + str3
str4

'Python & Numpy'

In [22]:
# O operador "+" aplicado a ndarrays não faz a concatenação, mas tentar somar elemento a elemento
a2D + b2D

ValueError: operands could not be broadcast together with shapes (3,9) (5,9) 

In [23]:
A = np.concatenate((a2D, b2D), axis = 0) # Concatenando pelo eixo das colunas (eixo 0) (empilhamento vertical) 
print("a2D")
print(a2D)
print("")
print("b2D")
print(b2D)
print("")
print("Concatenação")
print(A)

a2D
[[10 57 61 55 57 13  3 35 67]
 [ 6 58  1 18 47 54 21 44 23]
 [51 50 69 85 68 32 21 96 71]]

b2D
[[ 42  19  75  74  35 100  35  16  36]
 [ 98  35  88  25   7  24   7  30  41]
 [ 98  28  10   6  14  84  64  39  38]
 [ 80  77   2   6  62  28  73   4  95]
 [ 99  52  10   6  12  47  22  64  89]]

Concatenação
[[ 10  57  61  55  57  13   3  35  67]
 [  6  58   1  18  47  54  21  44  23]
 [ 51  50  69  85  68  32  21  96  71]
 [ 42  19  75  74  35 100  35  16  36]
 [ 98  35  88  25   7  24   7  30  41]
 [ 98  28  10   6  14  84  64  39  38]
 [ 80  77   2   6  62  28  73   4  95]
 [ 99  52  10   6  12  47  22  64  89]]


In [24]:
B = np.vstack((a2D, b2D)) # Concatenando pelo eixo das colunas (eixo 0) (empilhamento vertical) 
print("a2D")
print(a2D)
print("")
print("b2D")
print(b2D)
print("")
print("Concatenação")
print(B)

a2D
[[10 57 61 55 57 13  3 35 67]
 [ 6 58  1 18 47 54 21 44 23]
 [51 50 69 85 68 32 21 96 71]]

b2D
[[ 42  19  75  74  35 100  35  16  36]
 [ 98  35  88  25   7  24   7  30  41]
 [ 98  28  10   6  14  84  64  39  38]
 [ 80  77   2   6  62  28  73   4  95]
 [ 99  52  10   6  12  47  22  64  89]]

Concatenação
[[ 10  57  61  55  57  13   3  35  67]
 [  6  58   1  18  47  54  21  44  23]
 [ 51  50  69  85  68  32  21  96  71]
 [ 42  19  75  74  35 100  35  16  36]
 [ 98  35  88  25   7  24   7  30  41]
 [ 98  28  10   6  14  84  64  39  38]
 [ 80  77   2   6  62  28  73   4  95]
 [ 99  52  10   6  12  47  22  64  89]]


In [25]:
C = np.concatenate((b2D, c2D), axis = 1) # Concatenando pelo eixo das linhas (eixo 1) (empilhamento horizontal) 
print("b2D")
print(b2D)
print("")
print("c2D")
print(c2D)
print("")
print("Concatenação")
print(C)

b2D
[[ 42  19  75  74  35 100  35  16  36]
 [ 98  35  88  25   7  24   7  30  41]
 [ 98  28  10   6  14  84  64  39  38]
 [ 80  77   2   6  62  28  73   4  95]
 [ 99  52  10   6  12  47  22  64  89]]

c2D
[[44 52 69  3]
 [83 45 31 26]
 [78 88  4 30]
 [21 41 79 23]
 [49 58 27 58]]

Concatenação
[[ 42  19  75  74  35 100  35  16  36  44  52  69   3]
 [ 98  35  88  25   7  24   7  30  41  83  45  31  26]
 [ 98  28  10   6  14  84  64  39  38  78  88   4  30]
 [ 80  77   2   6  62  28  73   4  95  21  41  79  23]
 [ 99  52  10   6  12  47  22  64  89  49  58  27  58]]


In [26]:
D = np.hstack((b2D, c2D)) # Concatenando pelo eixo das linhas (eixo 1) (empilhamento horizontal) 
print("b2D")
print(b2D)
print("")
print("c2D")
print(c2D)
print("")
print("Concatenação")
print(D)

b2D
[[ 42  19  75  74  35 100  35  16  36]
 [ 98  35  88  25   7  24   7  30  41]
 [ 98  28  10   6  14  84  64  39  38]
 [ 80  77   2   6  62  28  73   4  95]
 [ 99  52  10   6  12  47  22  64  89]]

c2D
[[44 52 69  3]
 [83 45 31 26]
 [78 88  4 30]
 [21 41 79 23]
 [49 58 27 58]]

Concatenação
[[ 42  19  75  74  35 100  35  16  36  44  52  69   3]
 [ 98  35  88  25   7  24   7  30  41  83  45  31  26]
 [ 98  28  10   6  14  84  64  39  38  78  88   4  30]
 [ 80  77   2   6  62  28  73   4  95  21  41  79  23]
 [ 99  52  10   6  12  47  22  64  89  49  58  27  58]]


### Dividindo arrays

In [27]:
A_splitted = np.vsplit(A,2) # Divisáo vertical (corta no sentido das colunas)
print("Array original")
print(A)
print("")
print("1a parte")
print(A_splitted[0])
print("")
print("2a parte")
print(A_splitted[1])

Array original
[[ 10  57  61  55  57  13   3  35  67]
 [  6  58   1  18  47  54  21  44  23]
 [ 51  50  69  85  68  32  21  96  71]
 [ 42  19  75  74  35 100  35  16  36]
 [ 98  35  88  25   7  24   7  30  41]
 [ 98  28  10   6  14  84  64  39  38]
 [ 80  77   2   6  62  28  73   4  95]
 [ 99  52  10   6  12  47  22  64  89]]

1a parte
[[ 10  57  61  55  57  13   3  35  67]
 [  6  58   1  18  47  54  21  44  23]
 [ 51  50  69  85  68  32  21  96  71]
 [ 42  19  75  74  35 100  35  16  36]]

2a parte
[[98 35 88 25  7 24  7 30 41]
 [98 28 10  6 14 84 64 39 38]
 [80 77  2  6 62 28 73  4 95]
 [99 52 10  6 12 47 22 64 89]]


In [28]:
A_splitted3 = np.hsplit(A,3) # Divisão horizontal (corta no sentido das linhas)
print("Array original")
print(A)
print("")
print("1a parte")
print(A_splitted3[0])
print("")
print("2a parte")
print(A_splitted3[1])
print("")
print("3a parte")
print(A_splitted3[2])

Array original
[[ 10  57  61  55  57  13   3  35  67]
 [  6  58   1  18  47  54  21  44  23]
 [ 51  50  69  85  68  32  21  96  71]
 [ 42  19  75  74  35 100  35  16  36]
 [ 98  35  88  25   7  24   7  30  41]
 [ 98  28  10   6  14  84  64  39  38]
 [ 80  77   2   6  62  28  73   4  95]
 [ 99  52  10   6  12  47  22  64  89]]

1a parte
[[10 57 61]
 [ 6 58  1]
 [51 50 69]
 [42 19 75]
 [98 35 88]
 [98 28 10]
 [80 77  2]
 [99 52 10]]

2a parte
[[ 55  57  13]
 [ 18  47  54]
 [ 85  68  32]
 [ 74  35 100]
 [ 25   7  24]
 [  6  14  84]
 [  6  62  28]
 [  6  12  47]]

3a parte
[[ 3 35 67]
 [21 44 23]
 [21 96 71]
 [35 16 36]
 [ 7 30 41]
 [64 39 38]
 [73  4 95]
 [22 64 89]]
